services:
  app:
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_NAME=hexlet
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
    command: make dev
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  db_data: