services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: gyfdhsjb/devops-for-developers-project-74:latest
    command: make start

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hexlet
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U postgres"]
     interval: 10s
     timeout: 5s
     retries: 10
     start_period: 10s
volumes:
  db_data: