services:
  app:
    ports:
     - "8080:8080"
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: make dev