name: push

on:
  push:
    branches:
      - main

env:
  .CI: true
  APP_IMAGE_NAME: gyfdhsjb/devops-for-developers-project-74
  NGINX_IMAGE_NAME: gyfdhsjb/devops-for-developers-project-74-nginx
  COLOR_MAP: '{"success":"#008000","failure":"#800000"}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:latest
          cache-to: type=inline
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest

      - name: Run tests
        run: make ci

      - name: Build Nginx
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: services/web-nginx/Dockerfile
          tags: ${{ env.NGINX_IMAGE_NAME }}:latest

      #- name: Send notification into Slack
       # if: ${{ always() }}
       # uses: rtCamp/action-slack-notify@v2
       # env:
        #  SLACK_COLOR: ${{ fromJson(env.COLOR_MAP)[job.status] }}
        #  SLACK_TITLE: ${{ job.status }}
        #  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}